DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHORID BIGINT,
    GENREID BIGINT);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID BIGINT PRIMARY KEY,
    FULLNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255));

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
    ID BIGINT PRIMARY KEY,
    TEXT VARCHAR(255),
    BOOKID BIGINT);

DROP SEQUENCE IF EXISTS BOOK_SEQUENCE_ID;
CREATE SEQUENCE BOOK_SEQUENCE_ID START WITH 100 INCREMENT 1;

DROP SEQUENCE IF EXISTS AUTHOR_SEQUENCE_ID;
CREATE SEQUENCE AUTHOR_SEQUENCE_ID START WITH 100 INCREMENT 1;

DROP SEQUENCE IF EXISTS GENRE_SEQUENCE_ID;
CREATE SEQUENCE GENRE_SEQUENCE_ID START WITH 100 INCREMENT 1;

DROP SEQUENCE IF EXISTS COMMENT_SEQUENCE_ID;
CREATE SEQUENCE COMMENT_SEQUENCE_ID START WITH 100 INCREMENT 1;

drop table if exists userprofile;
create table userprofile(
    username varchar(50) not null primary key,
    password varchar(500) not null);
