DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHORID BIGINT,
    GENREID BIGINT);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY,
    FULLNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255));

DROP SEQUENCE IF EXISTS BOOKS_SEQUENCE_ID;
CREATE SEQUENCE BOOKS_SEQUENCE_ID START WITH 100 INCREMENT 1;

DROP SEQUENCE IF EXISTS AUTHORS_SEQUENCE_ID;
CREATE SEQUENCE AUTHORS_SEQUENCE_ID START WITH 100 INCREMENT 1;

DROP SEQUENCE IF EXISTS GENRES_SEQUENCE_ID;
CREATE SEQUENCE GENRES_SEQUENCE_ID START WITH 100 INCREMENT 1;
